### ISSUE TITLE
regression in IntelliJ support

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/plugin-pom#573]
### Jenkins and plugins versions report

WHen running a plugins unit test in intellij this no longer works out of the box with the plugin-pom `4.40` or higher.

This is in #524 the `argLine` was updated to use a surefire differed property, but IntelliJ [does not support this](https://youtrack.jetbrains.com/issue/IDEA-145991) in the default config.

Workaround is to not get surefire to parse the argline, however this does mean the the unit test can be run differently in the IDE than from maven due to different JVM settings.

<details>
  <summary>IntelliJ / plugin using plugin pom 4.40 or higher</summary>
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

in a clean intellij environment clone a plugin using plugin pom 4.40 or higher.

Select a unit test and run it

### Expected Results

intellij can not launch the test

### Actual Results

intellij launches the test and provides the result  (this is the behaviour using a parent prior to 4.40)

### Anything else?

this is an intellij bug, but more people seem to use intellij than eclipse (or other IDEs) so we may want to rework how we do the java module confuguration.

**Comment by jtnord** [comment]
Alas release notes are generally consulted at the time something is updated not later on.  A plugin may have multiple developers and other developers may not notice that.

I believe this issue makes things more prominent for those users.  I am not one of them as I use eclipse, but am aware of an amount of time lost due to this

**Comment by basil** [comment]
Released in [IntelliJ IDEA 2022.2](https://www.jetbrains.com/idea/whatsnew/2022-2/)
