### ISSUE TITLE
maven-enforcer-plugin reports missing dependencies on latest POM / BOM

### ISSUE THREAD

**Issue by offa** [jenkinsci/plugin-pom#586]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
BOM: 1508.v4b_d09ff0e893
POM: 4.43.1 (latest)
Jenkins: A LTS listed in BOM
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

- Linux / Windows (Jenkins CI)
- Linux (local)

### Reproduction steps

1. Update BOM or POM to latest versions (see examples below)
2. Build the project
3. Warnings appear

### Expected Results

No missing dependencies / warnings

### Actual Results

Warnings are issued for missing dependencies

Example:

```
[WARNING] Missing:
----------
1) org.jenkins-ci.plugins.workflow:workflow-step-api:jar:625.vd896b_f445a_f8

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.jenkins-ci.plugins.workflow -DartifactId=workflow-step-api -Dversion=625.vd896b_f445a_f8 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.jenkins-ci.plugins.workflow -DartifactId=workflow-step-api -Dversion=625.vd896b_f445a_f8 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.jenkins-ci.plugins.workflow:workflow-step-api:jar:625.vd896b_f445a_f8

----------
1 required artifact is missing.

for artifact: 
  org.jenkins-ci.plugins.workflow:workflow-step-api:jar:625.vd896b_f445a_f8

from the specified remote repositories:
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
Path to dependency: 
	1) org.jenkins-ci.plugins.workflow:workflow-step-api:jar:625.vd896b_f445a_f8
```

### Anything else?

Examples:

- https://github.com/jenkinsci/webhook-step-plugin/pull/114
- https://github.com/jenkinsci/credentials-plugin/pull/342

**Comment by jetersen** [comment]
This is already reported ashttps://github.com/mojohaus/extra-enforcer-rules/issues/225

Should be fixed by releasing: https://github.com/jenkinsci/plugin-pom/pull/581

cc @basil @timja @jtnord

**Comment by timja** [comment]
Released in https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.44

**Comment by offa** [comment]
Thanks for the quick fix!
