### ISSUE TITLE
`yarn mvntest` failures ignored in CI

### ISSUE THREAD

**Issue by jglick** [jenkinsci/plugin-pom#874]
In https://github.com/jenkinsci/workflow-cps-plugin/pull/821 I struggled to figure out how this ever passed in CI. Turns out

```bash
mvn verify -Dtest=InjectedTest -Dmaven.test.failure.ignore
```

prints ESLint failures but passes anyway. https://github.com/eirslett/frontend-maven-plugin#ignoring-failure does not say where test failures would be recorded. Based on inspecting sources, they are not recorded anywhere at all, so using `junit` is not enough. I think this mojo parameter needs to be disabled in the POM so that `maven.test.failure.ignore` applies only to Surefire.

**Comment by timja** [comment]
I don't believe the implementation was correct and I didn't get a chance to review it.

Re-opening it as I've filed an alternative: https://github.com/jenkinsci/plugin-pom/pull/1016
